### ISSUE TITLE
Fatal errors on activation

### ISSUE THREAD

**Issue by smutek** [kalenjohnson/source-theme#1]
Hey Kalen,

I was just checking this out and am getting "failed to open stream" fatal errors immediately after activating the theme. The only way to recover is by renaming the theme folder to deactivate.

I'm not sure if I'm doing anything wrong, but I'm having the same issue on both Desktop Server and a Vagrant box (VVV). Both environments are running PHP 5.5

Here's a quick screen cast - http://cl.ly/0b392Y37011c

**Comment by kalenjohnson** [comment]
Hi smutek, this version on Github is actually the full development version, so including the same npm bower gulp requirements, you also need to run Composer. At the moment it's just the PHP check, but `composer install`is still a requirement.

I definitely need to make a note of that. I've just been focusing on getting the release ready for the WP theme repo

**Comment by smutek** [comment]
Thanks Kalen!
